name: healthy_plate_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter Launcher Icons config (ROOT LEVEL, not under flutter:)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg_1.png
    - assets/images/bg_2.png
    - assets/images/food1.png
    - assets/images/food2.png
    - assets/images/food3.png
    - assets/images/stirfry.png
    - assets/images/cat.png
    - assets/images/google.png
    - assets/images/salad.png
    - assets/images/carbonara.png
    - assets/images/onigiri.png
    - assets/images/chickpea_curry.png
    - assets/images/avocado_toast.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Black.ttf
          weight: 800