// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALhhNK25Lq3OGKJnl9tEbkJhGHpn-lxGY',
    appId: '1:621760606382:android:851bef1f69d1f7d1d13d3f',
    messagingSenderId: '621760606382',
    projectId: 'healthyplateapp-8d323',
    storageBucket: 'healthyplateapp-8d323.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZtUzkGrYWMaPafMMvIRSSXC4i4cq7xQo',
    appId: '1:621760606382:ios:8bbdfed215108642d13d3f',
    messagingSenderId: '621760606382',
    projectId: 'healthyplateapp-8d323',
    storageBucket: 'healthyplateapp-8d323.firebasestorage.app',
    iosBundleId: 'com.example.healthyPlateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtHWTG19zWHk9IgEfkoj6h_jpX-f8RQrU',
    appId: '1:621760606382:web:9b1c5d6a48a202b3d13d3f',
    messagingSenderId: '621760606382',
    projectId: 'healthyplateapp-8d323',
    authDomain: 'healthyplateapp-8d323.firebaseapp.com',
    storageBucket: 'healthyplateapp-8d323.firebasestorage.app',
    measurementId: 'G-VP1WY4JYHB',
  );

}